export const LIST_JSONAPI_RESOURCE = 'LIST_JSONAPI_RESOURCE';
export type LIST_JSONAPI_RESOURCE = typeof LIST_JSONAPI_RESOURCE;

export const SHOW_JSONAPI_RESOURCE = 'SHOW_JSONAPI_RESOURCE';
export type SHOW_JSONAPI_RESOURCE = typeof SHOW_JSONAPI_RESOURCE;

export const PAGE_JSONAPI_RESOURCE = 'PAGE_JSONAPI_RESOURCE';
export type PAGE_JSONAPI_RESOURCE = typeof PAGE_JSONAPI_RESOURCE;

export const CREATE_JSONAPI_RESOURCE = 'CREATE_JSONAPI_RESOURCE';
export type CREATE_JSONAPI_RESOURCE = typeof CREATE_JSONAPI_RESOURCE;
